@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Create Report Export</h2>
    <form action="{{ route('report-exports.store') }}" method="POST">
        @csrf

        @if ($errors->any())
    <div class="alert alert-danger">
        <ul class="mb-0">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

        <div class="mb-3">
            <label>Type</label>
            <select name="type" class="form-control" required>
                <option value="">-- Select --</option>
                <option value="appointment">Appointment</option>
                <option value="sales">Sales</option>
                <option value="staff">Staff</option>
                <option value="inventory">Inventory</option>
                <option value="customer">Customer</option>
            </select>
        </div>

        <div class="mb-3">
            <label>Format</label>
            <select name="format" class="form-control" required>
                <option value="">-- Select --</option>
                <option value="pdf">PDF</option>
                <option value="excel">Excel</option>
            </select>
        </div>

        <div class="mb-3">
            <label>File Path</label>
            <input type="text" name="file_path" class="form-control" required>
        </div>

        <div class="mb-3">
            <label>Generated By (User ID)</label>
            <input type="number" name="generated_by" class="form-control" required>
        </div>

        <button class="btn btn-success">Submit</button>
    </form>
</div>
@endsection
