@extends('layouts.app')
@section('content')
<form action="{{ route('report-exports.update', $reportExport->id) }}" method="POST">
    @csrf
    @method('PUT')
    
     @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="mb-0">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
     @endif


    <div class="mb-3">
        <label>Type</label>
        <select name="type" class="form-control" required>
            <option value="appointment" {{ $reportExport->type == 'appointment' ? 'selected' : '' }}>Appointment</option>
            <option value="sales" {{ $reportExport->type == 'sales' ? 'selected' : '' }}>Sales</option>
            <option value="staff" {{ $reportExport->type == 'staff' ? 'selected' : '' }}>Staff</option>
            <option value="inventory" {{ $reportExport->type == 'inventory' ? 'selected' : '' }}>Inventory</option>
            <option value="customer" {{ $reportExport->type == 'customer' ? 'selected' : '' }}>Customer</option>
        </select>
    </div>

    <div class="mb-3">
        <label>Format</label>
        <select name="format" class="form-control" required>
            <option value="pdf" {{ $reportExport->format == 'pdf' ? 'selected' : '' }}>PDF</option>
            <option value="excel" {{ $reportExport->format == 'excel' ? 'selected' : '' }}>Excel</option>
        </select>
    </div>

    <div class="mb-3">
        <label>File Path</label>
        <input type="text" name="file_path" class="form-control" value="{{ old('file_path', $reportExport->file_path) }}" required>
    </div>

    <div class="mb-3">
        <label>Generated By (User ID)</label>
        <input type="number" name="generated_by" class="form-control" value="{{ old('generated_by', $reportExport->generated_by) }}" required>
    </div>

    <button type="submit" class="btn btn-success">Update Report</button>
</form>
@endsection