@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Report Exports</h2>
    <a href="{{ route('report-exports.create') }}" class="btn btn-primary mb-3">Add Report Export</a>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Type</th>
                <th>Format</th>
                <th>Generated By</th>
                <th>Exported At</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($exports as $export)
                <tr>
                    <td>{{ $export->id }}</td>
                    <td>{{ $export->type }}</td>
                    <td>{{ $export->format }}</td>
                    <td>{{ $export->generated_by }}</td>
                    <td>{{ $export->created_at }}</td>
                    <td>
                        <a href="{{ route('report-exports.edit', $export->id) }}" class="btn btn-sm btn-warning">Edit</a>
                        <form action="{{ route('report-exports.destroy', $export->id) }}" method="POST" class="d-inline">
                            @csrf @method('DELETE')
                            <button onclick="return confirm('Delete this export?')" class="btn btn-sm btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection
